version: '3'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: mi-contraseña
    ports:
      - "3306:3306"
  my-app:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql